// <auto-generated />
using System;
using BlogC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogC.Migrations
{
    [DbContext(typeof(NoticiasContext))]
    [Migration("20211201044537_AgregandoDato")]
    partial class AgregandoDato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlogC.Data.Models.NoticiasModels", b =>
                {
                    b.Property<Guid>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Texto")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdNoticia");

                    b.ToTable("Noticias");

                    b.HasData(
                        new
                        {
                            IdNoticia = new Guid("05f4f68e-9bb1-4e36-836c-0a9daec8736a"),
                            FechaCreacion = new DateTime(2021, 11, 30, 23, 45, 37, 3, DateTimeKind.Local).AddTicks(2433),
                            FechaModificacion = new DateTime(2021, 11, 30, 23, 45, 37, 4, DateTimeKind.Local).AddTicks(3724),
                            Imagen = "Imagenes/image1.png",
                            Texto = "Texto de Prueba para blog de noticias",
                            Titulo = "Texto de Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
