// <auto-generated />
using System;
using BlogC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogC.Migrations
{
    [DbContext(typeof(NoticiasContext))]
    [Migration("20211202060255_modificaVariables")]
    partial class modificaVariables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BlogC.Data.Models.NoticiasModels", b =>
                {
                    b.Property<Guid>("IdNoticia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNoticia");

                    b.ToTable("Noticias");

                    b.HasData(
                        new
                        {
                            IdNoticia = new Guid("05f4f68e-9bb1-4e36-836c-0a9daec8736a"),
                            FechaCreacion = new DateTime(2021, 12, 2, 1, 2, 54, 557, DateTimeKind.Local).AddTicks(9480),
                            FechaModificacion = new DateTime(2021, 12, 2, 1, 2, 54, 559, DateTimeKind.Local).AddTicks(2297),
                            Imagen = "Imagenes/image1.png",
                            Titulo = "Texto de Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
